#!/usr/bin/env python3
"""
PRD File Watcher — Context Handshake Protocol
Watches ACTIVE_PRD.md for changes and triggers Claude Code build sequence.

Usage:
    python3 scripts/watch-prd.py

Requirements:
    pip install watchdog

This script:
1. Watches ACTIVE_PRD.md for changes (modified time)
2. On change: logs to TEST_RESULTS.log + writes to TRIGGER_NEXT.md
3. Optionally triggers Claude Code via subprocess (requires user confirmation)
"""

import os
import sys
import time
import logging
from datetime import datetime
from pathlib import Path
from watchdog.observers import Observer
from watchdog.events import FileSystemEventHandler

# ---------------------------------------------------------------------------
# Configuration
# ---------------------------------------------------------------------------

ROOT_DIR = Path(__file__).parent.parent.parent
ACTIVE_PRD = ROOT_DIR / "ACTIVE_PRD.md"
TEST_RESULTS = ROOT_DIR / "TEST_RESULTS.log"
TRIGGER_NEXT = ROOT_DIR / "TRIGGER_NEXT.md"
SERVER_DIR = ROOT_DIR / "server"

logging.basicConfig(
    level=logging.INFO,
    format="%(asctime)s | %(levelname)s | %(message)s",
    datefmt="%Y-%m-%dT%H:%M:%S",
)
logger = logging.getLogger("PRD-Watcher")


# ---------------------------------------------------------------------------
# File Operations
# ---------------------------------------------------------------------------

def log_trigger(reason: str) -> None:
    """Append a trigger event to TEST_RESULTS.log."""
    timestamp = datetime.utcnow().strftime("%Y-%m-%dT%H:%M:%SZ")
    entry = f"[{timestamp}] | SYSTEM | PRD_FILE_CHANGED | TRIGGERED | {reason}\n"

    with open(TEST_RESULTS, "a") as f:
        f.write(entry)

    logger.info(f"Logged trigger: {reason}")


def write_trigger_file(module: str, action: str) -> None:
    """Write to TRIGGER_NEXT.md to signal next action."""
    timestamp = datetime.utcnow().strftime("%Y-%m-%dT%H:%M:%SZ")
    content = f"""# TRIGGER_NEXT.md
# Auto-generated by PRD Watcher — DO NOT EDIT MANUALLY
# Generated: {timestamp}

target_module: {module}
triggered_action: {action}
triggered_at: {timestamp}

## Instructions for Claude Code

1. Read ACTIVE_PRD.md to understand the current module target
2. Execute the build sequence for: {action}
3. Run QA tests: `cd server && npm test`
4. Update TEST_RESULTS.log with results
5. Clear this file after completing the action

## How to Trigger

Edit ACTIVE_PRD.md and this file will automatically detect the change.
Then run: `cd server && npm run dev` (to start the server)
And: `npm test` (to run QA tests)
"""

    with open(TRIGGER_NEXT, "w") as f:
        f.write(content)

    logger.info(f"Trigger file written: {module} -> {action}")


def read_active_prd() -> str:
    """Extract current target module from ACTIVE_PRD.md."""
    if not ACTIVE_PRD.exists():
        return "UNKNOWN"

    content = ACTIVE_PRD.read_text()

    # Find "Current target module:" line
    for line in content.split("\n"):
        if "target module:" in line.lower() or "current target" in line.lower():
            # Extract the module name
            parts = line.split(":", 1)
            if len(parts) > 1:
                return parts[1].strip()

    # Fallback: find status lines
    for line in content.split("\n"):
        if "Module 1.1" in line and "NOT STARTED" in line:
            return "Module 1.1: Auth Context Verification"
        if "Module 1.2" in line and "PENDING" in line:
            return "Module 1.2: Cassandra Two-Layer Auth"

    return "UNKNOWN"


def try_start_server() -> bool:
    """Attempt to start the Fastify server in the background."""
    try:
        import subprocess
        import signal

        # Check if server is already running
        import urllib.request
        try:
            urllib.request.urlopen("http://localhost:3001/health", timeout=1)
            logger.info("Server already running at http://localhost:3001")
            return True
        except Exception:
            pass

        # Start server in background
        server_script = SERVER_DIR / "node_modules" / ".bin" / "tsx"
        if not server_script.exists():
            logger.warning(f"Server script not found: {server_script}")
            logger.info("To start server manually: cd server && npm install && npm run dev")
            return False

        logger.info("Starting Fastify server...")
        subprocess.Popen(
            [str(server_script), "watch", "src/index.ts"],
            cwd=str(SERVER_DIR),
            stdout=subprocess.DEVNULL,
            stderr=subprocess.DEVNULL,
        )
        time.sleep(2)  # Give server time to start

        # Verify it started
        try:
            urllib.request.urlopen("http://localhost:3001/health", timeout=2)
            logger.info("Server started successfully!")
            return True
        except Exception:
            logger.warning("Server started but health check failed")
            return False

    except Exception as e:
        logger.warning(f"Could not auto-start server: {e}")
        return False


# ---------------------------------------------------------------------------
# File System Handler
# ---------------------------------------------------------------------------

class PRDFileHandler(FileSystemEventHandler):
    """Handles file system events for ACTIVE_PRD.md."""

    def __init__(self):
        self.last_modified = 0.0
        self.debounce_seconds = 1.0

    def on_modified(self, event):
        # Only respond to ACTIVE_PRD.md
        if os.path.basename(event.src_path) != ACTIVE_PRD.name:
            return

        # Debounce: ignore rapid successive events
        now = time.time()
        if now - self.last_modified < self.debounce_seconds:
            return
        self.last_modified = now

        logger.info(f"Detected change in {ACTIVE_PRD.name}")

        # Read current target
        target = read_active_prd()

        # Log the trigger
        log_trigger(f"ACTIVE_PRD.md modified — current target: {target}")

        # Write trigger file
        write_trigger_file(target, f"Build {target}")

        # Try to start server
        server_started = try_start_server()

        print("\n" + "=" * 60)
        print("📋 PRD CHANGE DETECTED")
        print("=" * 60)
        print(f"Target module: {target}")
        print(f"Server status:  {'Running' if server_started else 'Not running'}")
        print(f"Health check:  http://localhost:3001/health")
        print(f"Tests:          cd server && npm test")
        print("=" * 60 + "\n")


# ---------------------------------------------------------------------------
# Main
# ---------------------------------------------------------------------------

def main():
    logger.info("=" * 50)
    logger.info("PRD Watcher — Context Handshake Protocol")
    logger.info("=" * 50)

    # Verify files exist
    if not ACTIVE_PD.exists():
        logger.error(f"ACTIVE_PRD.md not found at {ACTIVE_PRD}")
        logger.info("Creating default ACTIVE_PRD.md...")
        ACTIVE_PRD.write_text("""# Active PRD
target_module: Module 1.1: Auth Context Verification
status: NOT STARTED
""")
        logger.info(f"Created {ACTIVE_PRD}")

    logger.info(f"Watching: {ACTIVE_PRD}")
    logger.info(f"Logging to: {TEST_RESULTS}")
    logger.info("")

    # Start watching
    event_handler = PRDFileHandler()
    observer = Observer()
    observer.schedule(event_handler, str(ACTIVE_PRD.parent), recursive=False)
    observer.start()

    logger.info("👀 Watching for PRD changes...")
    logger.info("Press Ctrl+C to stop.\n")

    try:
        while True:
            time.sleep(1)
    except KeyboardInterrupt:
        logger.info("\nStopping watcher...")
        observer.stop()

    observer.join()
    logger.info("Watcher stopped.")


if __name__ == "__main__":
    main()
